[pytest]
testpaths = tests
pythonpath = .
addopts =
    --html=reports/report.html
    --self-contained-html
    --alluredir=allure-results
    -v
    --tb=short
markers =
    smoke: Smoke tests
    regression: Regression tests
    bulk_transfer_db2_mssql: Bulk transfer DB2 to MSSQL tests
    bulk_transfer_db2_postgres: Bulk transfer DB2 to Postgres tests
    bulk_transfer_vsam_mssql: Bulk transfer VSAM to MSSQL tests
    release_30_05_25: Release 30-05-25 tests
    release_27_06_25: Release 27-06-25 tests
filterwarnings =
    ignore:datetime\.datetime\.utcnow\(\) is deprecated.*:DeprecationWarning:openpyxl\.packaging\.core
